### ISSUE TITLE
Use API Key instead of password

### ISSUE THREAD

**Issue by shield-9** [horike37/wp-one-metric#1]
I think this should be fixed before stable release.
IMO, [google/google-api-php-client](https://github.com/google/google-api-php-client) is the best solution. (See also: [Google Developers](https://developers.google.com/api-client-library/php/?hl=en))

I'll tackle this problem in my free time.

From: @horike37's [Facebook Post](https://www.facebook.com/horike.takahiro/posts/778622878854000?comment_id=778837142165907&offset=0&total_comments=4)

**Comment by horike37** [comment]
Fixed if. This Commit 2dc8bace5858a652ec4ac813f8eb4ec5c1b47df5
