### ISSUE TITLE
.csv button action overriding "Search Posts"

### ISSUE THREAD

**Issue by ghost** [horike37/wp-one-metric#5]
When on the Posts page, entering a search and then hitting the "Search Posts" button downloads the one metric .csv instead of searching.

**Comment by horike37** [comment]
I fixed it the following [2308e914cc117cb264fb6c5ddb7e7083fe7d2061](https://github.com/horike37/wp-one-metric/commit/2308e914cc117cb264fb6c5ddb7e7083fe7d2061)
Thanks
